### PR TITLE
Fixed conflicts in the libadwaita part

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
Hey merge this also, this is the final edit

**Comment by soumyaDghosh** [comment]
portals will do the job

**Comment by soumyaDghosh** [comment]
An app must access only those what it needs

**Comment by CapeCrusader321** [comment]
> An app must access only those what it needs

The dbus issue still persists apparmor wont own the common id either ?/

**Comment by soumyaDghosh** [comment]
> > An app must access only those what it needs
> 
> The dbus issue still persists apparmor wont own the common id either ??

give me some logs please

**Comment by CapeCrusader321** [comment]
> > > An app must access only those what it needs
> > 
> > 
> > The dbus issue still persists apparmor wont own the common id either ??
> 
> give me some logs please

Download and Install from here as dangerous mode after removing any curtail snap builds if installed --> https://launchpad.net/~build.snapcraft.io/+snap/8d4b5fb3d46434d264a474b445c7f410/+build/2076620/+files/curtail_1.7.0_amd64.snap

I will try using snappy-debug but i recommend you yourself see this

**Comment by soumyaDghosh** [comment]
> > > > An app must access only those what it needs
> > > 
> > > 
> > > The dbus issue still persists apparmor wont own the common id either ??
> > 
> > 
> > give me some logs please
> 
> Download and Install from here as dangerous mode after removing any curtail snap builds if installed --> https://launchpad.net/~build.snapcraft.io/+snap/8d4b5fb3d46434d264a474b445c7f410/+build/2076620/+files/curtail_1.7.0_amd64.snap
> 
> I will try using snappy-debug but i recommend you yourself see this

Firstly, the github actions, already give you the snap after building, no need to rely on snapcraft. And I already use it...
I have that pr creator also, who tested it. Works fine. Show me some screenshots or terminal logs. Let me check. This can happen though.
image

**Comment by soumyaDghosh** [comment]
Fixed it... don't make unnecessary changes in this repo. Please keep it clean, as changes from me are becoming conflicting ones with yours. Please use you local repo for testing

**Comment by CapeCrusader321** [comment]
> > > > > An app must access only those what it needs
> > > > 
> > > > 
> > > > The dbus issue still persists apparmor wont own the common id either ??
> > > 
> > > 
> > > give me some logs please
> > 
> > 
> > Download and Install from here as dangerous mode after removing any curtail snap builds if installed --> https://launchpad.net/~build.snapcraft.io/+snap/8d4b5fb3d46434d264a474b445c7f410/+build/2076620/+files/curtail_1.7.0_amd64.snap
> > I will try using snappy-debug but i recommend you yourself see this
> 
> Firstly, the github actions, already give you the snap after building, no need to rely on snapcraft. And I already use it... I have that pr creator also, who tested it. Works fine. Show me some screenshots or terminal logs. Let me check. This can happen though. image

Here You Go -:


sc06
sc07

**Comment by soumyaDghosh** [comment]
I should suggest you delete this repo, you must not make always changes directly in your repo. And please write meaningful commit messages. Why are you messing this up. No one will be able to understand this repo later.
I have the snapcraft.yaml file. Create a fresh repo and connect it with snapcraft.

**Pull request merged**
